Election/Election/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('voting.urls')),
    
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', user_views.LogoutView,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Election/Parties/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'parties'

urlpatterns = [
    path('create/', views.create_party, name='party_form'),  # Use views.create_party here
]

Election/voting/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,vote,results

urlpatterns = [
    path("", home, name="home"),
    path('vote/',vote,name = 'vote' ),
    path('results/', results, name='results'),
    path('party/', include('Parties.urls')),
]

Election/Parties/models.py
from django.db import models
from PIL import Image
# Create your models here.


class Party(models.Model):
    name = models.CharField(max_length=100)
    propaganda = models.TextField()
    logo = models.ImageField(default='default.jpeg', upload_to='party_logos', max_length=255) 
    votes = models.IntegerField(default=0)
    president = models.CharField(max_length=100)
    vicepresident = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        logo = Image.open(self.logo.path)
        if logo.height > 300 or logo.width > 300:
            output_size = (300, 300)
            logo.thumbnail(output_size)
            logo.save(self.logo.path)

Election/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    regno = models.CharField(max_length=20, unique=True)
    branch = models.CharField(max_length=100)
    semester = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username
    

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         UserProfile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.userprofile.save()

Election/voting/models.py
from django.db import models
from Parties.models import Party
from django.contrib.auth.models import User

# Create your models here.
class Vote(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    party = models.ForeignKey(Party, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

Election/Parties/forms.py
from django import forms
from .models import Party

class PartyForm(forms.ModelForm):
    class Meta:
        model = Party
        fields = ['name', 'propaganda', 'logo', 'president', 'vicepresident']
    

Election/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile

class UserRegisterForm(UserCreationForm):
    regno = forms.CharField(max_length=20)
    branch = forms.CharField(max_length=100)
    semester = forms.CharField(max_length=10)

    class Meta:
        model = User
        fields = ['username', 'regno', 'branch', 'semester', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            user_profile = UserProfile.objects.create(
                user=user,
                regno=self.cleaned_data['regno'],
                branch=self.cleaned_data['branch'],
                semester=self.cleaned_data['semester']
            )
            user_profile.save()
        return user

Election/Parties/views.py
from django.shortcuts import render, redirect
from .forms import PartyForm
from .models import Party

def create_party(request):
    if request.method == 'POST':
        form = PartyForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')  
    else:
        form = PartyForm()
    return render(request, 'parties/party_form.html', {'form': form})

Election/users/views.py
from django.shortcuts import render,redirect

from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth import logout
# Create your views here.



def register(request):
    if request.method == 'POST':
        form =UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Acc created for {username}!!')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request,'users/register.html',{'form':form})

def LogoutView(request):
    logout(request)
    return render(request, 'users/logout.html')

Election/voting/views.py
from django.shortcuts import render,redirect
from Parties.models import Party
from .models import Vote
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def home(request):
    context = { 
        'parties' : Party.objects.all()
    }    
    return render(request, 'voting/home.html', context)


@login_required
def vote(request):
    user_vote = Vote.objects.filter(user=request.user).first()
    if request.method == 'POST':
        if user_vote:
            messages.error(request, 'You have already voted.')
            return redirect('vote')

        party_id = request.POST.get('party_id')
        if party_id:
            try:
                party = Party.objects.get(id=party_id)
                Vote.objects.create(user=request.user, party=party)
                party.votes += 1
                party.save()
                messages.success(request, 'Your vote has been recorded.')
            except Party.DoesNotExist:
                messages.error(request, 'Invalid party selected.')
        return redirect('vote')

    context = { 
        'parties': Party.objects.all(),
        'user_vote': user_vote
    }
    return render(request, 'voting/vote.html', context)

@login_required
def results(request):
    if not request.user.is_superuser:
        messages.warning(request, 'You do not have permission to check the results NOW!!!')
        return redirect('home')
    else:
        parties = Party.objects.all()
        context = {
            'parties': parties
        }
        return render(request, 'voting/results.html', context)

Election/Parties/templates/Parties/party_form.html
{% extends 'voting/base.html' %}

{% block content %}
<div class="container">
    <h2>Register your Party</h2>
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <br>
        <fieldset class="form-group">
            <label for="id_name" class="label">Name</label>
            {{ form.name }}
        </fieldset>
        <fieldset class="form-group">
            <label for="id_propaganda" class="label">Propaganda</label>
            {{ form.propaganda }}
        </fieldset>
        <fieldset class="form-group">
            <label for="id_logo" class="label">Logo</label>
            {{ form.logo }}
        </fieldset>
        <fieldset class="form-group">
            <label for="id_president" class="label">President</label>
            {{ form.president }}
        </fieldset>
        <fieldset class="form-group">
            <label for="id_vicepresident" class="label">Vice President</label>
            {{ form.vicepresident }}
        </fieldset>

        <input class="submit" type="submit" value="Save Party" />
    </form>
</div>
{% endblock %}

Election/users/templates/users/login.html
{% extends 'voting/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class = "content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            dont Have an ACC? <a class="ml-2" href="{% url 'register'%}">Sign Up now</a>
        </small>
    </div>
  </div>

{% endblock content %}

Election/users/templates/users/logout.html
{% extends 'voting/base.html' %}

{% block content %}
  
    <h2>You Have been Logged Out </h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}" class="text-centered">Log In</a>
        </small>
    </div>


{% endblock content %}

Election/users/templates/users/register.html
{% extends 'voting/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class = "content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Register Now</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have an ACC? <a class="ml-2" href="#">Sign In</a>
        </small>
    </div>
  </div>

{% endblock content %}

Election/voting/templates/voting/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%static 'voting/main.css' %}">            

    {%if title %}
        <title>{{title}}</title>
    {% else %}
        <title>Django</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'parties:party_form' %}"> Create Your Party</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'home' %}"style="color: white;">Home</a>
                <a class="nav-item nav-link" href="#"style="color: white;">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'vote' %}" style="color: white;">Vote Here</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}" style="color: white;">Logout</a>
                <a class="nav-item nav-link" href="{% url 'results' %}" style="color: white;">Result</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}" style="color: white;">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}" style="color: white;">Register</a>
                {%endif%}
              
            </div>
          </div>
        </nav>
    </header>
    


    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
          <!-- <div class="col-md-4">
            <div class="content-section"> -->
              <!-- <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p> -->
            <!-- </div>
          </div> -->
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Election/voting/templates/voting/home.html
{% extends 'voting/base.html' %}

{% block title %}
    <title>Home</title>
{% endblock title %}

{% block content %}
    <h1 class="text-center mb-5">Welcome to the College Voting System</h1>
    {% if user.is_authenticated %}
    <div class="d-flex justify-content-center">
        <a class="text-center mb-5" href="{% url 'vote' %}" style="font-size: 20px;">Click Here to Cast Your Vote</a>
    </div>
    
    {%endif%}
    
    <div class="row">
        <div class="col-md-10">
            <div class="row mt-4">
                

                {% for party in parties %}
                    <div class="col-md-6 col-lg-4 mb-4 d-flex justify-content-center">
                        <div class="card" style="background-color: #14da3c;">
                            <div class="first-content" >
                                <div class="text-center" >
                                    {% if party.logo %}
                                        <img class="rounded-circle article-img" src="{{ party.logo.url }}">
                                    {% endif %}
                                    <h2>{{ party.name }}</h2>
                                    <p><strong>President:</strong> {{ party.president }}</p>
                                    <p><strong>Vice President:</strong> {{ party.vicepresident }}</p>
                                </div>
                            </div>
                            <div class="second-content" style="background-color: #467500;">
                                <span>{{ party.propaganda }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

Election/voting/templates/voting/results.html
{% extends 'voting/base.html' %}

{% block content %}
  <h2>Election Results</h2>
  <table>
    <thead>
      <tr>
        <th>Party</th>
        <th>Votes</th>
      </tr>
    </thead>
    <tbody>
      {% for party in parties %}
        <tr>
          <td>{{ party.name }}</td>
          <td>{{ party.votes }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Election/voting/templates/voting/vote.html
{% extends 'voting/base.html' %}

{% block content %}
  <h2>Vote</h2>
  {% if messages %}
    <ul>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if user_vote %}
    <p>You have already voted for {{ user_vote.party.name }}.</p>
  {% else %}
    <form method="post">
      {% csrf_token %}
      {% for party in parties %}
        <div>
          <input type="radio" id="party{{ party.id }}" name="party_id" value="{{ party.id }}">
          <label for="party{{ party.id }}">{{ party.name }}</label>
        </div>
      {% endfor %}
      <button type="submit">Vote</button>
    </form>
  {% endif %}
{% endblock %}